// <auto-generated />
namespace CrossfitDiary.DAL.EF.DataContexts.CrossfitDiaryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_IsAlternative_Property_Exercise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_IsAlternative_Property_Exercise));
        
        string IMigrationMetadata.Id
        {
            get { return "201612280702059_Add_IsAlternative_Property_Exercise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
