// <auto-generated />
namespace CrossfitDiary.DAL.EF.DataContexts.CrossfitDiaryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MeasureType_Add_Column_ShortDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MeasureType_Add_Column_ShortDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201611220710538_MeasureType_Add_Column_ShortDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
