// <auto-generated />
namespace CrossfitDiary.DAL.EF.DataContexts.CrossfitDiaryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ParentWorkouts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ParentWorkouts));
        
        string IMigrationMetadata.Id
        {
            get { return "201806060552102_ParentWorkouts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
