// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace CrossfitDiary.Web.Controllers
{
    public partial class CrossfitterController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CrossfitterController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ManageWorkout()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManageWorkout);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CrossfitterController Actions { get { return MVC.Crossfitter; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Crossfitter";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Crossfitter";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string CreateNewWorkout = "CreateNewWorkout";
            public readonly string LogWorkout = "LogWorkout";
            public readonly string ManageWorkout = "ManageWorkout";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string CreateNewWorkout = "CreateNewWorkout";
            public const string LogWorkout = "LogWorkout";
            public const string ManageWorkout = "ManageWorkout";
        }


        static readonly ActionParamsClass_ManageWorkout s_params_ManageWorkout = new ActionParamsClass_ManageWorkout();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ManageWorkout ManageWorkoutParams { get { return s_params_ManageWorkout; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ManageWorkout
        {
            public readonly string date = "date";
            public readonly string workoutId = "workoutId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CreateNewWorkout = "CreateNewWorkout";
                public readonly string LogWorkout = "LogWorkout";
                public readonly string ManageWorkout = "ManageWorkout";
            }
            public readonly string CreateNewWorkout = "~/Views/Crossfitter/CreateNewWorkout.cshtml";
            public readonly string LogWorkout = "~/Views/Crossfitter/LogWorkout.cshtml";
            public readonly string ManageWorkout = "~/Views/Crossfitter/ManageWorkout.cshtml";
            static readonly _TemplatesClass s_Templates = new _TemplatesClass();
            public _TemplatesClass Templates { get { return s_Templates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _TemplatesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _CreateNewWorkout = "_CreateNewWorkout";
                    public readonly string _ExistingWorkoutsTemplate = "_ExistingWorkoutsTemplate";
                    public readonly string _LogWorkoutPartial = "_LogWorkoutPartial";
                    public readonly string _RoutineInfoTemplate = "_RoutineInfoTemplate";
                    public readonly string _SimpleRoutineItemTemlate = "_SimpleRoutineItemTemlate";
                }
                public readonly string _CreateNewWorkout = "~/Views/Crossfitter/Templates/_CreateNewWorkout.cshtml";
                public readonly string _ExistingWorkoutsTemplate = "~/Views/Crossfitter/Templates/_ExistingWorkoutsTemplate.cshtml";
                public readonly string _LogWorkoutPartial = "~/Views/Crossfitter/Templates/_LogWorkoutPartial.cshtml";
                public readonly string _RoutineInfoTemplate = "~/Views/Crossfitter/Templates/_RoutineInfoTemplate.cshtml";
                public readonly string _SimpleRoutineItemTemlate = "~/Views/Crossfitter/Templates/_SimpleRoutineItemTemlate.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_CrossfitterController : CrossfitDiary.Web.Controllers.CrossfitterController
    {
        public T4MVC_CrossfitterController() : base(Dummy.Instance) { }

        [NonAction]
        partial void CreateNewWorkoutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateNewWorkout()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateNewWorkout);
            CreateNewWorkoutOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LogWorkoutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LogWorkout()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogWorkout);
            LogWorkoutOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ManageWorkoutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.DateTime? date, int? workoutId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ManageWorkout(System.DateTime? date, int? workoutId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManageWorkout);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "date", date);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "workoutId", workoutId);
            ManageWorkoutOverride(callInfo, date, workoutId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
