// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static CrossfitDiary.Web.Controllers.AccountController Account = new CrossfitDiary.Web.Controllers.T4MVC_AccountController();
    public static CrossfitDiary.Web.Controllers.AdminController Admin = new CrossfitDiary.Web.Controllers.T4MVC_AdminController();
    public static CrossfitDiary.Web.Controllers.CrossfitterController Crossfitter = new CrossfitDiary.Web.Controllers.T4MVC_CrossfitterController();
    public static CrossfitDiary.Web.Controllers.HomeController Home = new CrossfitDiary.Web.Controllers.T4MVC_HomeController();
    public static CrossfitDiary.Web.Controllers.TeacherController Teacher = new CrossfitDiary.Web.Controllers.T4MVC_TeacherController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        public const string UrlPath = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class BaseTypeScript {
            public const string UrlPath = "~/Scripts/BaseTypeScript";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string BaseService_ts = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/BaseService.min.js") ? Url("BaseService.min.js") : Url("BaseService.js");
            public static readonly string CrossfitterService_ts = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/CrossfitterService.min.js") ? Url("CrossfitterService.min.js") : Url("CrossfitterService.js");
            public static readonly string ServerProcessedViewModel_ts = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ServerProcessedViewModel.min.js") ? Url("ServerProcessedViewModel.min.js") : Url("ServerProcessedViewModel.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class bootstrap_datepicker {
            public const string UrlPath = "~/Scripts/bootstrap-datepicker";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string bootstrap_datetimepicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-datetimepicker.min.js") ? Url("bootstrap-datetimepicker.min.js") : Url("bootstrap-datetimepicker.js");
            public static readonly string bootstrap_datetimepicker_min_js = Url("bootstrap-datetimepicker.min.js");
            public static readonly string moment_with_locales_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/moment-with-locales.min.js") ? Url("moment-with-locales.min.js") : Url("moment-with-locales.js");
            public static readonly string moment_with_locales_min_js = Url("moment-with-locales.min.js");
            public static readonly string moment_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/moment.min.js") ? Url("moment.min.js") : Url("moment.js");
            public static readonly string moment_min_js = Url("moment.min.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class bootstrap_select {
            public const string UrlPath = "~/Scripts/bootstrap-select";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string bootstrap_select_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-select.min.js") ? Url("bootstrap-select.min.js") : Url("bootstrap-select.js");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class i18n {
                public const string UrlPath = "~/Scripts/bootstrap-select/i18n";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string defaults_ar_AR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-ar_AR.min.js") ? Url("defaults-ar_AR.min.js") : Url("defaults-ar_AR.js");
                public static readonly string defaults_bg_BG_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-bg_BG.min.js") ? Url("defaults-bg_BG.min.js") : Url("defaults-bg_BG.js");
                public static readonly string defaults_cro_CRO_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-cro_CRO.min.js") ? Url("defaults-cro_CRO.min.js") : Url("defaults-cro_CRO.js");
                public static readonly string defaults_cs_CZ_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-cs_CZ.min.js") ? Url("defaults-cs_CZ.min.js") : Url("defaults-cs_CZ.js");
                public static readonly string defaults_da_DK_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-da_DK.min.js") ? Url("defaults-da_DK.min.js") : Url("defaults-da_DK.js");
                public static readonly string defaults_de_DE_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-de_DE.min.js") ? Url("defaults-de_DE.min.js") : Url("defaults-de_DE.js");
                public static readonly string defaults_en_US_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-en_US.min.js") ? Url("defaults-en_US.min.js") : Url("defaults-en_US.js");
                public static readonly string defaults_es_CL_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-es_CL.min.js") ? Url("defaults-es_CL.min.js") : Url("defaults-es_CL.js");
                public static readonly string defaults_eu_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-eu.min.js") ? Url("defaults-eu.min.js") : Url("defaults-eu.js");
                public static readonly string defaults_fa_IR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-fa_IR.min.js") ? Url("defaults-fa_IR.min.js") : Url("defaults-fa_IR.js");
                public static readonly string defaults_fi_FI_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-fi_FI.min.js") ? Url("defaults-fi_FI.min.js") : Url("defaults-fi_FI.js");
                public static readonly string defaults_fr_FR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-fr_FR.min.js") ? Url("defaults-fr_FR.min.js") : Url("defaults-fr_FR.js");
                public static readonly string defaults_hu_HU_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-hu_HU.min.js") ? Url("defaults-hu_HU.min.js") : Url("defaults-hu_HU.js");
                public static readonly string defaults_id_ID_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-id_ID.min.js") ? Url("defaults-id_ID.min.js") : Url("defaults-id_ID.js");
                public static readonly string defaults_it_IT_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-it_IT.min.js") ? Url("defaults-it_IT.min.js") : Url("defaults-it_IT.js");
                public static readonly string defaults_ko_KR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-ko_KR.min.js") ? Url("defaults-ko_KR.min.js") : Url("defaults-ko_KR.js");
                public static readonly string defaults_lt_LT_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-lt_LT.min.js") ? Url("defaults-lt_LT.min.js") : Url("defaults-lt_LT.js");
                public static readonly string defaults_nb_NO_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-nb_NO.min.js") ? Url("defaults-nb_NO.min.js") : Url("defaults-nb_NO.js");
                public static readonly string defaults_nl_NL_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-nl_NL.min.js") ? Url("defaults-nl_NL.min.js") : Url("defaults-nl_NL.js");
                public static readonly string defaults_pl_PL_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-pl_PL.min.js") ? Url("defaults-pl_PL.min.js") : Url("defaults-pl_PL.js");
                public static readonly string defaults_pt_BR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-pt_BR.min.js") ? Url("defaults-pt_BR.min.js") : Url("defaults-pt_BR.js");
                public static readonly string defaults_pt_PT_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-pt_PT.min.js") ? Url("defaults-pt_PT.min.js") : Url("defaults-pt_PT.js");
                public static readonly string defaults_ro_RO_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-ro_RO.min.js") ? Url("defaults-ro_RO.min.js") : Url("defaults-ro_RO.js");
                public static readonly string defaults_ru_RU_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-ru_RU.min.js") ? Url("defaults-ru_RU.min.js") : Url("defaults-ru_RU.js");
                public static readonly string defaults_sk_SK_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-sk_SK.min.js") ? Url("defaults-sk_SK.min.js") : Url("defaults-sk_SK.js");
                public static readonly string defaults_sl_SI_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-sl_SI.min.js") ? Url("defaults-sl_SI.min.js") : Url("defaults-sl_SI.js");
                public static readonly string defaults_sv_SE_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-sv_SE.min.js") ? Url("defaults-sv_SE.min.js") : Url("defaults-sv_SE.js");
                public static readonly string defaults_tr_TR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-tr_TR.min.js") ? Url("defaults-tr_TR.min.js") : Url("defaults-tr_TR.js");
                public static readonly string defaults_ua_UA_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-ua_UA.min.js") ? Url("defaults-ua_UA.min.js") : Url("defaults-ua_UA.js");
                public static readonly string defaults_zh_CN_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-zh_CN.min.js") ? Url("defaults-zh_CN.min.js") : Url("defaults-zh_CN.js");
                public static readonly string defaults_zh_TW_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/defaults-zh_TW.min.js") ? Url("defaults-zh_TW.min.js") : Url("defaults-zh_TW.js");
            }
        
        }
    
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Crossfitter {
            public const string UrlPath = "~/Scripts/Crossfitter";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string CrossfitterController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/CrossfitterController.min.js") ? Url("CrossfitterController.min.js") : Url("CrossfitterController.js");
            public static readonly string ExerciseMeasureType_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ExerciseMeasureType.min.js") ? Url("ExerciseMeasureType.min.js") : Url("ExerciseMeasureType.js");
            public static readonly string ExerciseMeasureTypeValue_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ExerciseMeasureTypeValue.min.js") ? Url("ExerciseMeasureTypeValue.min.js") : Url("ExerciseMeasureTypeValue.js");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class ManageWorkout {
                public const string UrlPath = "~/Scripts/Crossfitter/ManageWorkout";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string ChooseExistingWorkoutController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ChooseExistingWorkoutController.min.js") ? Url("ChooseExistingWorkoutController.min.js") : Url("ChooseExistingWorkoutController.js");
                public static readonly string CreateWorkoutController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/CreateWorkoutController.min.js") ? Url("CreateWorkoutController.min.js") : Url("CreateWorkoutController.js");
                public static readonly string LogWorkoutController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/LogWorkoutController.min.js") ? Url("LogWorkoutController.min.js") : Url("LogWorkoutController.js");
                public static readonly string ManageWorkoutController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ManageWorkoutController.min.js") ? Url("ManageWorkoutController.min.js") : Url("ManageWorkoutController.js");
            }
        
            public static readonly string SimpleRoutine_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/SimpleRoutine.min.js") ? Url("SimpleRoutine.min.js") : Url("SimpleRoutine.js");
            public static readonly string WorkoutType_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/WorkoutType.min.js") ? Url("WorkoutType.min.js") : Url("WorkoutType.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Home {
            public const string UrlPath = "~/Scripts/Home";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string HomePageController_ts = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/HomePageController.min.js") ? Url("HomePageController.min.js") : Url("HomePageController.js");
        }
    
        public static readonly string jquery_3_1_1_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-3.1.1.intellisense.min.js") ? Url("jquery-3.1.1.intellisense.min.js") : Url("jquery-3.1.1.intellisense.js");
        public static readonly string jquery_3_1_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-3.1.1.min.js") ? Url("jquery-3.1.1.min.js") : Url("jquery-3.1.1.js");
        public static readonly string jquery_3_1_1_min_js = Url("jquery-3.1.1.min.js");
        public static readonly string jquery_3_1_1_min_map = Url("jquery-3.1.1.min.map");
        public static readonly string jquery_3_1_1_slim_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-3.1.1.slim.min.js") ? Url("jquery-3.1.1.slim.min.js") : Url("jquery-3.1.1.slim.js");
        public static readonly string jquery_3_1_1_slim_min_js = Url("jquery-3.1.1.slim.min.js");
        public static readonly string jquery_3_1_1_slim_min_map = Url("jquery-3.1.1.slim.min.map");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class jqueryPlugins {
            public const string UrlPath = "~/Scripts/jqueryPlugins";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string jquery_inputmask_bundle_min_js = Url("jquery.inputmask.bundle.min.js");
        }
    
        public static readonly string knockout_3_4_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/knockout-3.4.0.min.js") ? Url("knockout-3.4.0.min.js") : Url("knockout-3.4.0.js");
        public static readonly string knockout_validation_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/knockout.validation.min.js") ? Url("knockout.validation.min.js") : Url("knockout.validation.js");
        public static readonly string knockout_validation_min_js = Url("knockout.validation.min.js");
        public static readonly string ko_bindingHandlers_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ko.bindingHandlers.min.js") ? Url("ko.bindingHandlers.min.js") : Url("ko.bindingHandlers.js");
        public static readonly string modernizr_2_8_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/modernizr-2.8.3.min.js") ? Url("modernizr-2.8.3.min.js") : Url("modernizr-2.8.3.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Spinner {
            public const string UrlPath = "~/Scripts/Spinner";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class typings {
            public const string UrlPath = "~/Scripts/typings";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class jquery {
                public const string UrlPath = "~/Scripts/typings/jquery";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string jquery_d_ts = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.d.min.js") ? Url("jquery.d.min.js") : Url("jquery.d.js");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class knockout {
                public const string UrlPath = "~/Scripts/typings/knockout";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string knockout_d_ts = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/knockout.d.min.js") ? Url("knockout.d.min.js") : Url("knockout.d.js");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class q {
                public const string UrlPath = "~/Scripts/typings/q";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string Q_d_ts = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Q.d.min.js") ? Url("Q.d.min.js") : Url("Q.d.js");
                public static readonly string q_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/q.min.js") ? Url("q.min.js") : Url("q.js");
                public static readonly string q_min_js = Url("q.min.js");
            }
        
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        public const string UrlPath = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string _bootstrap_datetimepicker_less = Url("_bootstrap-datetimepicker.less");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class bootstrap {
            public const string UrlPath = "~/Content/bootstrap";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string alerts_less = Url("alerts.less");
            public static readonly string badges_less = Url("badges.less");
            public static readonly string bootstrap_social_less = Url("bootstrap-social.less");
            public static readonly string bootstrap_less = Url("bootstrap.less");
            public static readonly string breadcrumbs_less = Url("breadcrumbs.less");
            public static readonly string button_groups_less = Url("button-groups.less");
            public static readonly string buttons_less = Url("buttons.less");
            public static readonly string carousel_less = Url("carousel.less");
            public static readonly string close_less = Url("close.less");
            public static readonly string code_less = Url("code.less");
            public static readonly string component_animations_less = Url("component-animations.less");
            public static readonly string dropdowns_less = Url("dropdowns.less");
            public static readonly string forms_less = Url("forms.less");
            public static readonly string glyphicons_less = Url("glyphicons.less");
            public static readonly string grid_less = Url("grid.less");
            public static readonly string input_groups_less = Url("input-groups.less");
            public static readonly string jumbotron_less = Url("jumbotron.less");
            public static readonly string labels_less = Url("labels.less");
            public static readonly string list_group_less = Url("list-group.less");
            public static readonly string media_less = Url("media.less");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class mixins {
                public const string UrlPath = "~/Content/bootstrap/mixins";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string alerts_less = Url("alerts.less");
                public static readonly string background_variant_less = Url("background-variant.less");
                public static readonly string border_radius_less = Url("border-radius.less");
                public static readonly string buttons_less = Url("buttons.less");
                public static readonly string center_block_less = Url("center-block.less");
                public static readonly string clearfix_less = Url("clearfix.less");
                public static readonly string forms_less = Url("forms.less");
                public static readonly string gradients_less = Url("gradients.less");
                public static readonly string grid_framework_less = Url("grid-framework.less");
                public static readonly string grid_less = Url("grid.less");
                public static readonly string hide_text_less = Url("hide-text.less");
                public static readonly string image_less = Url("image.less");
                public static readonly string labels_less = Url("labels.less");
                public static readonly string list_group_less = Url("list-group.less");
                public static readonly string nav_divider_less = Url("nav-divider.less");
                public static readonly string nav_vertical_align_less = Url("nav-vertical-align.less");
                public static readonly string opacity_less = Url("opacity.less");
                public static readonly string pagination_less = Url("pagination.less");
                public static readonly string panels_less = Url("panels.less");
                public static readonly string progress_bar_less = Url("progress-bar.less");
                public static readonly string reset_filter_less = Url("reset-filter.less");
                public static readonly string reset_text_less = Url("reset-text.less");
                public static readonly string resize_less = Url("resize.less");
                public static readonly string responsive_visibility_less = Url("responsive-visibility.less");
                public static readonly string size_less = Url("size.less");
                public static readonly string tab_focus_less = Url("tab-focus.less");
                public static readonly string table_row_less = Url("table-row.less");
                public static readonly string text_emphasis_less = Url("text-emphasis.less");
                public static readonly string text_overflow_less = Url("text-overflow.less");
                public static readonly string vendor_prefixes_less = Url("vendor-prefixes.less");
            }
        
            public static readonly string mixins_less = Url("mixins.less");
            public static readonly string modals_less = Url("modals.less");
            public static readonly string navbar_less = Url("navbar.less");
            public static readonly string navs_less = Url("navs.less");
            public static readonly string normalize_less = Url("normalize.less");
            public static readonly string pager_less = Url("pager.less");
            public static readonly string pagination_less = Url("pagination.less");
            public static readonly string panels_less = Url("panels.less");
            public static readonly string popovers_less = Url("popovers.less");
            public static readonly string print_less = Url("print.less");
            public static readonly string progress_bars_less = Url("progress-bars.less");
            public static readonly string responsive_embed_less = Url("responsive-embed.less");
            public static readonly string responsive_utilities_less = Url("responsive-utilities.less");
            public static readonly string scaffolding_less = Url("scaffolding.less");
            public static readonly string tables_less = Url("tables.less");
            public static readonly string theme_less = Url("theme.less");
            public static readonly string thumbnails_less = Url("thumbnails.less");
            public static readonly string tooltip_less = Url("tooltip.less");
            public static readonly string type_less = Url("type.less");
            public static readonly string utilities_less = Url("utilities.less");
            public static readonly string variables_less = Url("variables.less");
            public static readonly string wells_less = Url("wells.less");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class bootstrap_datepicker {
            public const string UrlPath = "~/Content/bootstrap-datepicker";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string bootstrap_datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-datepicker.min.css") ? Url("bootstrap-datepicker.min.css") : Url("bootstrap-datepicker.css");
        }
    
        public static readonly string bootstrap_datetimepicker_build_less = Url("bootstrap-datetimepicker-build.less");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class bootstrap_select {
            public const string UrlPath = "~/Content/bootstrap-select";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string bootstrap_select_less = Url("bootstrap-select.less");
            public static readonly string variables_less = Url("variables.less");
        }
    
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
        public static readonly string bootstrap_less = Url("bootstrap.less");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Configuration {
            public const string UrlPath = "~/Content/Configuration";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class css {
            public const string UrlPath = "~/Content/css";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string font_awesome_min_css = Url("font-awesome.min.css");
        }
    
        public static readonly string custom_variables_less = Url("custom-variables.less");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class fonts {
            public const string UrlPath = "~/Content/fonts";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string fontawesome_webfont_eot = Url("fontawesome-webfont.eot");
            public static readonly string fontawesome_webfont_svg = Url("fontawesome-webfont.svg");
            public static readonly string fontawesome_webfont_ttf = Url("fontawesome-webfont.ttf");
            public static readonly string fontawesome_webfont_woff = Url("fontawesome-webfont.woff");
            public static readonly string fontawesome_webfont_woff2 = Url("fontawesome-webfont.woff2");
            public static readonly string FontAwesome_otf = Url("FontAwesome.otf");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class img {
            public const string UrlPath = "~/Content/img";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string curly_bracket_svg = Url("curly-bracket.svg");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class pages {
            public const string UrlPath = "~/Content/pages";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class crossfitter {
                public const string UrlPath = "~/Content/pages/crossfitter";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class create_workout {
                    public const string UrlPath = "~/Content/pages/crossfitter/create-workout";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string create_workout_less = Url("create-workout.less");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class log_workout {
                    public const string UrlPath = "~/Content/pages/crossfitter/log-workout";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string log_workout_less = Url("log-workout.less");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class manage_workout {
                    public const string UrlPath = "~/Content/pages/crossfitter/manage-workout";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string existing_workouts_container_less = Url("existing-workouts-container.less");
                    public static readonly string manage_workout_less = Url("manage-workout.less");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class workout_info {
                    public const string UrlPath = "~/Content/pages/crossfitter/workout-info";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string workout_info_less = Url("workout-info.less");
                }
            
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class home {
                public const string UrlPath = "~/Content/pages/home";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string home_less = Url("home.less");
                public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
                public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
            }
        
            public static readonly string login_page_less = Url("login-page.less");
            public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
            public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            public const string UrlPath = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @base {
                public const string UrlPath = "~/Content/themes/base";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string accordion_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/accordion.min.css") ? Url("accordion.min.css") : Url("accordion.css");
                public static readonly string all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/all.min.css") ? Url("all.min.css") : Url("all.css");
                public static readonly string autocomplete_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/autocomplete.min.css") ? Url("autocomplete.min.css") : Url("autocomplete.css");
                public static readonly string base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/base.min.css") ? Url("base.min.css") : Url("base.css");
                public static readonly string button_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/button.min.css") ? Url("button.min.css") : Url("button.css");
                public static readonly string core_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/core.min.css") ? Url("core.min.css") : Url("core.css");
                public static readonly string datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/datepicker.min.css") ? Url("datepicker.min.css") : Url("datepicker.css");
                public static readonly string dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dialog.min.css") ? Url("dialog.min.css") : Url("dialog.css");
                public static readonly string draggable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/draggable.min.css") ? Url("draggable.min.css") : Url("draggable.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    public const string UrlPath = "~/Content/themes/base/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                    public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                    public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                    public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                    public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                    public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                    public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                    public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                    public static readonly string ui_icons_444444_256x240_png = Url("ui-icons_444444_256x240.png");
                    public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                    public static readonly string ui_icons_555555_256x240_png = Url("ui-icons_555555_256x240.png");
                    public static readonly string ui_icons_777620_256x240_png = Url("ui-icons_777620_256x240.png");
                    public static readonly string ui_icons_777777_256x240_png = Url("ui-icons_777777_256x240.png");
                    public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                    public static readonly string ui_icons_cc0000_256x240_png = Url("ui-icons_cc0000_256x240.png");
                    public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                    public static readonly string ui_icons_ffffff_256x240_png = Url("ui-icons_ffffff_256x240.png");
                }
            
                public static readonly string jquery_ui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-ui.min.css") ? Url("jquery-ui.min.css") : Url("jquery-ui.css");
                public static readonly string jquery_ui_min_css = Url("jquery-ui.min.css");
                public static readonly string menu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/menu.min.css") ? Url("menu.min.css") : Url("menu.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class minified {
                    public const string UrlPath = "~/Content/themes/base/minified";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class images {
                        public const string UrlPath = "~/Content/themes/base/minified/images";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    }
                
                }
            
                public static readonly string progressbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/progressbar.min.css") ? Url("progressbar.min.css") : Url("progressbar.css");
                public static readonly string resizable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/resizable.min.css") ? Url("resizable.min.css") : Url("resizable.css");
                public static readonly string selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/selectable.min.css") ? Url("selectable.min.css") : Url("selectable.css");
                public static readonly string selectmenu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/selectmenu.min.css") ? Url("selectmenu.min.css") : Url("selectmenu.css");
                public static readonly string slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/slider.min.css") ? Url("slider.min.css") : Url("slider.css");
                public static readonly string sortable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/sortable.min.css") ? Url("sortable.min.css") : Url("sortable.css");
                public static readonly string spinner_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/spinner.min.css") ? Url("spinner.min.css") : Url("spinner.css");
                public static readonly string tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/tabs.min.css") ? Url("tabs.min.css") : Url("tabs.css");
                public static readonly string theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/theme.min.css") ? Url("theme.min.css") : Url("theme.css");
                public static readonly string tooltip_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/tooltip.min.css") ? Url("tooltip.min.css") : Url("tooltip.css");
            }
        
        }
    
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class BaseTypeScript 
            {
                public static class Assets
                {
                }
            }
            public static partial class bootstrap_datepicker 
            {
                public static class Assets
                {
                    public const string bootstrap_datetimepicker_js = "~/Scripts/bootstrap-datepicker/bootstrap-datetimepicker.js"; 
                    public const string bootstrap_datetimepicker_min_js = "~/Scripts/bootstrap-datepicker/bootstrap-datetimepicker.min.js"; 
                    public const string moment_with_locales_js = "~/Scripts/bootstrap-datepicker/moment-with-locales.js"; 
                    public const string moment_with_locales_min_js = "~/Scripts/bootstrap-datepicker/moment-with-locales.min.js"; 
                    public const string moment_js = "~/Scripts/bootstrap-datepicker/moment.js"; 
                    public const string moment_min_js = "~/Scripts/bootstrap-datepicker/moment.min.js"; 
                }
            }
            public static partial class bootstrap_select 
            {
                public static partial class i18n 
                {
                    public static class Assets
                    {
                        public const string defaults_ar_AR_js = "~/Scripts/bootstrap-select/i18n/defaults-ar_AR.js"; 
                        public const string defaults_bg_BG_js = "~/Scripts/bootstrap-select/i18n/defaults-bg_BG.js"; 
                        public const string defaults_cro_CRO_js = "~/Scripts/bootstrap-select/i18n/defaults-cro_CRO.js"; 
                        public const string defaults_cs_CZ_js = "~/Scripts/bootstrap-select/i18n/defaults-cs_CZ.js"; 
                        public const string defaults_da_DK_js = "~/Scripts/bootstrap-select/i18n/defaults-da_DK.js"; 
                        public const string defaults_de_DE_js = "~/Scripts/bootstrap-select/i18n/defaults-de_DE.js"; 
                        public const string defaults_en_US_js = "~/Scripts/bootstrap-select/i18n/defaults-en_US.js"; 
                        public const string defaults_es_CL_js = "~/Scripts/bootstrap-select/i18n/defaults-es_CL.js"; 
                        public const string defaults_eu_js = "~/Scripts/bootstrap-select/i18n/defaults-eu.js"; 
                        public const string defaults_fa_IR_js = "~/Scripts/bootstrap-select/i18n/defaults-fa_IR.js"; 
                        public const string defaults_fi_FI_js = "~/Scripts/bootstrap-select/i18n/defaults-fi_FI.js"; 
                        public const string defaults_fr_FR_js = "~/Scripts/bootstrap-select/i18n/defaults-fr_FR.js"; 
                        public const string defaults_hu_HU_js = "~/Scripts/bootstrap-select/i18n/defaults-hu_HU.js"; 
                        public const string defaults_id_ID_js = "~/Scripts/bootstrap-select/i18n/defaults-id_ID.js"; 
                        public const string defaults_it_IT_js = "~/Scripts/bootstrap-select/i18n/defaults-it_IT.js"; 
                        public const string defaults_ko_KR_js = "~/Scripts/bootstrap-select/i18n/defaults-ko_KR.js"; 
                        public const string defaults_lt_LT_js = "~/Scripts/bootstrap-select/i18n/defaults-lt_LT.js"; 
                        public const string defaults_nb_NO_js = "~/Scripts/bootstrap-select/i18n/defaults-nb_NO.js"; 
                        public const string defaults_nl_NL_js = "~/Scripts/bootstrap-select/i18n/defaults-nl_NL.js"; 
                        public const string defaults_pl_PL_js = "~/Scripts/bootstrap-select/i18n/defaults-pl_PL.js"; 
                        public const string defaults_pt_BR_js = "~/Scripts/bootstrap-select/i18n/defaults-pt_BR.js"; 
                        public const string defaults_pt_PT_js = "~/Scripts/bootstrap-select/i18n/defaults-pt_PT.js"; 
                        public const string defaults_ro_RO_js = "~/Scripts/bootstrap-select/i18n/defaults-ro_RO.js"; 
                        public const string defaults_ru_RU_js = "~/Scripts/bootstrap-select/i18n/defaults-ru_RU.js"; 
                        public const string defaults_sk_SK_js = "~/Scripts/bootstrap-select/i18n/defaults-sk_SK.js"; 
                        public const string defaults_sl_SI_js = "~/Scripts/bootstrap-select/i18n/defaults-sl_SI.js"; 
                        public const string defaults_sv_SE_js = "~/Scripts/bootstrap-select/i18n/defaults-sv_SE.js"; 
                        public const string defaults_tr_TR_js = "~/Scripts/bootstrap-select/i18n/defaults-tr_TR.js"; 
                        public const string defaults_ua_UA_js = "~/Scripts/bootstrap-select/i18n/defaults-ua_UA.js"; 
                        public const string defaults_zh_CN_js = "~/Scripts/bootstrap-select/i18n/defaults-zh_CN.js"; 
                        public const string defaults_zh_TW_js = "~/Scripts/bootstrap-select/i18n/defaults-zh_TW.js"; 
                    }
                }
                public static class Assets
                {
                    public const string bootstrap_select_js = "~/Scripts/bootstrap-select/bootstrap-select.js"; 
                }
            }
            public static partial class Crossfitter 
            {
                public static partial class ManageWorkout 
                {
                    public static class Assets
                    {
                        public const string ChooseExistingWorkoutController_js = "~/Scripts/Crossfitter/ManageWorkout/ChooseExistingWorkoutController.js"; 
                        public const string CreateWorkoutController_js = "~/Scripts/Crossfitter/ManageWorkout/CreateWorkoutController.js"; 
                        public const string LogWorkoutController_js = "~/Scripts/Crossfitter/ManageWorkout/LogWorkoutController.js"; 
                        public const string ManageWorkoutController_js = "~/Scripts/Crossfitter/ManageWorkout/ManageWorkoutController.js"; 
                    }
                }
                public static class Assets
                {
                    public const string CrossfitterController_js = "~/Scripts/Crossfitter/CrossfitterController.js"; 
                    public const string ExerciseMeasureType_js = "~/Scripts/Crossfitter/ExerciseMeasureType.js"; 
                    public const string ExerciseMeasureTypeValue_js = "~/Scripts/Crossfitter/ExerciseMeasureTypeValue.js"; 
                    public const string SimpleRoutine_js = "~/Scripts/Crossfitter/SimpleRoutine.js"; 
                    public const string WorkoutType_js = "~/Scripts/Crossfitter/WorkoutType.js"; 
                }
            }
            public static partial class Home 
            {
                public static class Assets
                {
                }
            }
            public static partial class jqueryPlugins 
            {
                public static class Assets
                {
                    public const string jquery_inputmask_bundle_min_js = "~/Scripts/jqueryPlugins/jquery.inputmask.bundle.min.js"; 
                }
            }
            public static partial class Spinner 
            {
                public static class Assets
                {
                }
            }
            public static partial class typings 
            {
                public static partial class jquery 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class knockout 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class q 
                {
                    public static class Assets
                    {
                        public const string q_js = "~/Scripts/typings/q/q.js"; 
                        public const string q_min_js = "~/Scripts/typings/q/q.min.js"; 
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public const string _references_js = "~/Scripts/_references.js"; 
                public const string bootstrap_min_js = "~/Scripts/bootstrap.min.js"; 
                public const string jquery_3_1_1_intellisense_js = "~/Scripts/jquery-3.1.1.intellisense.js"; 
                public const string jquery_3_1_1_js = "~/Scripts/jquery-3.1.1.js"; 
                public const string jquery_3_1_1_min_js = "~/Scripts/jquery-3.1.1.min.js"; 
                public const string jquery_3_1_1_slim_js = "~/Scripts/jquery-3.1.1.slim.js"; 
                public const string jquery_3_1_1_slim_min_js = "~/Scripts/jquery-3.1.1.slim.min.js"; 
                public const string knockout_3_4_0_js = "~/Scripts/knockout-3.4.0.js"; 
                public const string knockout_validation_js = "~/Scripts/knockout.validation.js"; 
                public const string knockout_validation_min_js = "~/Scripts/knockout.validation.min.js"; 
                public const string ko_bindingHandlers_js = "~/Scripts/ko.bindingHandlers.js"; 
                public const string modernizr_2_8_3_js = "~/Scripts/modernizr-2.8.3.js"; 
            }
        }
        public static partial class Content 
        {
            public static partial class bootstrap 
            {
                public static partial class mixins 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class bootstrap_datepicker 
            {
                public static class Assets
                {
                    public const string bootstrap_datepicker_css = "~/Content/bootstrap-datepicker/bootstrap-datepicker.css";
                }
            }
            public static partial class bootstrap_select 
            {
                public static class Assets
                {
                }
            }
            public static partial class Configuration 
            {
                public static class Assets
                {
                }
            }
            public static partial class css 
            {
                public static class Assets
                {
                    public const string font_awesome_min_css = "~/Content/css/font-awesome.min.css";
                }
            }
            public static partial class fonts 
            {
                public static class Assets
                {
                }
            }
            public static partial class img 
            {
                public static class Assets
                {
                }
            }
            public static partial class pages 
            {
                public static partial class crossfitter 
                {
                    public static partial class create_workout 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class log_workout 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class manage_workout 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class workout_info 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static partial class home 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class themes 
            {
                public static partial class @base 
                {
                    public static partial class images 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class minified 
                    {
                        public static partial class images 
                        {
                            public static class Assets
                            {
                            }
                        }
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                        public const string accordion_css = "~/Content/themes/base/accordion.css";
                        public const string all_css = "~/Content/themes/base/all.css";
                        public const string autocomplete_css = "~/Content/themes/base/autocomplete.css";
                        public const string base_css = "~/Content/themes/base/base.css";
                        public const string button_css = "~/Content/themes/base/button.css";
                        public const string core_css = "~/Content/themes/base/core.css";
                        public const string datepicker_css = "~/Content/themes/base/datepicker.css";
                        public const string dialog_css = "~/Content/themes/base/dialog.css";
                        public const string draggable_css = "~/Content/themes/base/draggable.css";
                        public const string jquery_ui_css = "~/Content/themes/base/jquery-ui.css";
                        public const string jquery_ui_min_css = "~/Content/themes/base/jquery-ui.min.css";
                        public const string menu_css = "~/Content/themes/base/menu.css";
                        public const string progressbar_css = "~/Content/themes/base/progressbar.css";
                        public const string resizable_css = "~/Content/themes/base/resizable.css";
                        public const string selectable_css = "~/Content/themes/base/selectable.css";
                        public const string selectmenu_css = "~/Content/themes/base/selectmenu.css";
                        public const string slider_css = "~/Content/themes/base/slider.css";
                        public const string sortable_css = "~/Content/themes/base/sortable.css";
                        public const string spinner_css = "~/Content/themes/base/spinner.css";
                        public const string tabs_css = "~/Content/themes/base/tabs.css";
                        public const string theme_css = "~/Content/themes/base/theme.css";
                        public const string tooltip_css = "~/Content/themes/base/tooltip.css";
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public const string bootstrap_css = "~/Content/bootstrap.css";
                public const string bootstrap_min_css = "~/Content/bootstrap.min.css";
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


